name: Create and publish a Docker image

on:
  push:
    branches: ["main"]

jobs:
  build-and-push-image:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      jelastic_env: ofn-producer
    secrets:
      jelastic_access_token: ${{ secrets.JELASTIC_ACCESS_TOKEN }}
      shopify_api_key: ${{ secrets.SHOPIFY_API_KEY_PRODUCTION }}
